sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: NE94lRA6gEZXhayALfD7b73bh6jOstSp7uLpmFgc2+e4vZ7HM+7XFLqLS3lXadAFDutZ+A2nHhi78E4ECUoDiekccwABZyV0j1B5rQpUu+sDp1UhqjP3KqUtaWYqvIYbnyNbad4WfZtMHXFPlQPo9ef/9kjMJ0S3glRM6Ia6fNUq2WsD4konkXi49wpYt5+r39DbGG4Wjxxs5+0AAS3eU9Dq9BSRswd36xoPGX99V5+Z/F0OUpCTdegD11shjP13uSU+Gszqzt3FuGGRbQ2Glb6hWYIXtwZqSsEsN0B5vEVJrmilc1v9DQAk6fen2KImz4OmZVYlaWGTlImO7iT+Gd1wrS75ZQZCdbNFg0qlrDqfRp/4jGjIc3UfOQY7NVKuBP0pckrCGTw3G3T+G3SG9hooOmLCYvtOsPsuxSWyhlIDa8WdQSEXl3Cv/9heSMQ2P+gPgLq5B6k3+uqUi10Xid59vTtmQWLvC7cciUcWyybjIMEq47JsnEYme2RjHVGd73NGDCLuzjHz+qcGo20xM7Em+XAO+kTIpIF1/AkF6Kt2bh41aa3RC9hWvIW71qQ/cubz12/FgnVpYzGu3Z5HgMvwG3ScEsuAP5TynnPBGCKh5KSi6OrM2iujdbtLUk0rhY0aXtyi6KKIhGNUCMIXGCYXc6yZohvLWF//wjsxxVA=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Legends-of-the-Jews-Volume-2_1494
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy